/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jninative_HelloJNI */

#ifndef _Included_jninative_HelloJNI
#define _Included_jninative_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jninative_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jninative_HelloJNI_sayHello(JNIEnv *env, jobject thisObj);

#ifdef __cplusplus
}
#endif
#endif
